# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: macOS tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v3

    # swift-actions/setup-swift@v1.25.0 seems to use macosx10.15.4, Swift 5.9.0, and Xcode_14.2
    - uses: swift-actions/setup-swift@v1.25.0       
      with:
        swift-version: "5.9"

    # - name: Build
    #   run: swift build -v
    - name: Run tests
      run: swift test
